language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
cache: bundler
before_install:
  - 'psql -c "create database db/test;" -U postgres'
before-script: 
  - 'bundle exec rake db:create'
  - 'bundle exec rake db:migrate'